version: "3.3"

services:
  
  cassandra:
    container_name: cassandra
    image: cassandra:2.1.21
    ports:
      - 7199:7199 # JMX
      - 7000:7000 # cluster communication
      - 7001:7001 # cluster communication (SSL)
      - 9042:9042 # native protocol clients
      - 9160:9160 # thrift clients      
    environment:
      - KEY1=VALUE1
      - KEY1=VALUE2
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:2.1.21
    depends_on:
      - cassandra
    volumes:
      - ./src/main/resources/cql:/cql 
      - ./src/main/scripts:/scripts
    entrypoint: [
      "/scripts/wait-for-it.sh",
      "-s",
      "-t",
      "600",
      "cassandra:9042",
      "--",
      "bash",
      "-c",
      "cqlsh cassandra -f /cql/customer_schema.cql"
    ]
